Upgrade to latest OTP 26
Avoid this error:
```
ERROR: OTP release 25 does not match required regex 26|27|28
ERROR: compile failed while processing /home/runner/work/clouseau/clouseau/deps/couchdb.main/src/snappy: rebar_abort
```