Cleanup Configuration (#155)
* Bump python to `3.14.3`

Fix the following errors in GitHub Actions:

```log
...
  mise ERROR Failed to install core:python@3.12.7: No GitHub artifact attestations found for python@3.12.7
  To disable attestation verification, set MISE_PYTHON_GITHUB_ATTESTATIONS=false
  or add `python.github_attestations = false` to your mise config
  mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
Error: The process '/home/runner/.local/share/mise/bin/mise' failed with exit code 1
```

* Remove `_root_` from import statements

`_root_` is used in import statements to prevent internal project
packages from shadowing system library packages with the same name.
However, given that all source code resides within the
`com.cloudant.ziose` package, removing `_root_` should be fine.

* Remove `final` from case objects

Case objects are inherently singleton instances and cannot be
inherited from or extended. Therefore, remove `final` from them.

* Remove `asInstanceOf[String]`

The type of the `default` parameter is String, so remove the
redundant `asInstanceOf[String]`.

* Remove unused metric `field_cache_metrics`

* Reorder `WorkerConfiguration`

* Refactor `CapacityConfiguration` and extract some comments

* Update tests in `ConfigSpec.scala`

- Extract common functions to avoid redundancy.
- Add a test to handle cases where the capacity is not specified
  in the configuration file.